# BT2101 K-Means and Hierarchical Clustering

## 1 Goal

In this notebook, we will explore clustering method, an unsupervised learning method, including:
* K-Means Clustering
* Hierarchical Clustering

In [1]:
# -*- coding:utf-8 -*-
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from __future__ import division
from math import sqrt
%matplotlib inline

### 1.1 K-Means Clustering

K-Means Clustering steps:

1. Determine the number of k (i.e., number of clusters)
2. Randomly select k centroids (i.e. centers of clusters)
3. Assign each data point to its closest centroid
4. Recalculate the centroids as the average of all data points in a cluster
5. Assign data points to their closest centroids
6. Repeat Step 4 and 5 until the observations are not reassigned or the maximum number of iterations is reached

http://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html

In [2]:
# Load libraries and dataset
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

# Load data
filepath = './iris.csv'
colnames = ['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'class']
feature_list =  ['sepal_length', 'sepal_width', 'petal_length', 'petal_width']
#iris = pd.read_csv(filepath, header=None, names=colnames, dtype={'sepal_length':np.float64, 'sepal_width':np.float64, 'petal_length':np.float64, 'petal_width':np.float64})
iris = pd.read_csv(filepath)
features = iris[feature_list]

# Standardize features: Z-index
# http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html
scaler = StandardScaler()
features_std = scaler.fit_transform(features)

In [3]:
# Fit k-means clustering model: Suppose 3 clusters
cluster_3 = KMeans(n_clusters=3, random_state=0, n_jobs=-1)
model_3 = cluster_3.fit(features) # Clustering without feature standardization
model_std_3 = cluster_3.fit(features_std) # Clustering after feature standardization

In [4]:
# View cluster centers for each cluster:
model_std_3.cluster_centers_

array([[ 1.13597027,  0.09659843,  0.996271  ,  1.01717187],
       [-1.01457897,  0.84230679, -1.30487835, -1.25512862],
       [-0.05021989, -0.88029181,  0.34753171,  0.28206327]])

In [5]:
# View predicted clusters:
model_std_3.labels_

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 0, 0, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 0,
       2, 2, 2, 2, 0, 2, 2, 2, 2, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2, 0, 0, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0,
       0, 0, 0, 2, 2, 0, 0, 0, 0, 2, 0, 2, 0, 2, 0, 0, 2, 0, 0, 0, 0, 0,
       0, 2, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 0, 2, 0, 0, 2], dtype=int32)

In [6]:
# Compare with true classes:
# Remember usually you have no output labels in the dataset used for clustering
iris['species'].values

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolo

In [7]:
# Predict which cluster is a new observation in:
new_obs = [[0.5, 0.5, 0.5, 0.5]]
model_std_3.predict(new_obs)

array([0], dtype=int32)

### How to choose k? 
#### Elbow method
* Gauge how the heterogeneity within clusters changes for various of k.
* The heterogeneity within clusters is expected to decreases with more clusters.
* The heterogeneity is measured by within-clusters/groups sum of squares (WSS)

\begin{align}
WSS(k) = \mathop{\sum}_{i=1}^{N}\mathop{\sum}_{j=0}^{p}(x_{ij}-centroid(x_{kj}))^2
\end{align}

Suppose N observations and p features. <br/>
k is cluster id ($=1,...,K$). <br/>
$x_{ij}$ is $i^{th}$ observation $j^{th}$ feature. <br/>
$centroid(x_{kj})$ is $k^{th}$ centroid of feature $j$.

In [8]:
# Import scipy used for calculate distances
from scipy.spatial.distance import cdist

References: https://docs.scipy.org/doc/scipy/reference/spatial.distance.html

In [ ]:
# Cluster data with 1-10 clusters and get centroids

N_cluster = range(1, 11) # Assume number of 1 to 10 clusters
WSS_list = [] # A list of WSS for 1 to 10 clusters

for k in N_cluster:
    
    # Run k-means model
    cluster = KMeans(n_clusters=k, random_state=0, n_jobs=-1) # Run the model with k clusters: k from 1 to 10
    model = cluster.fit(features_std) # Fit the data with standardized features
    centroids = model.cluster_centers_ # Get centroids for each cluster id (=0,...,k-1)
    labels = model.labels_ # Get labels (which cluster id) for each observation
    
    # Calculate WSS(k)
    squared_distance = cdist(features_std, centroids, 'sqeuclidean') # Calculate squared distance between each observation and k centroids
    #min_distance_cluster_id = np.argmin(squared_distance, axis=1) # Find the index of minimum squared distance for each observation
    min_distance = np.min(squared_distance, axis=1) # Find minimum squared distance for each observation
    WSS = np.sum(min_distance)
    
    WSS_list.append(WSS)   
    

In [ ]:
# Show WSS for 1-10 clusters
WSS_list

In [ ]:
# Plot the elbow curve
fig = plt.figure()
ax = fig.add_subplot(1, 1, 1)
ax.plot(N_cluster, WSS_list, 'g*-')
ax.plot(N_cluster[1], WSS_list[1], marker='o', markersize=12, markeredgewidth=2, markeredgecolor='r', markerfacecolor='None')
ax.plot(N_cluster[2], WSS_list[2], marker='o', markersize=12, markeredgewidth=2, markeredgecolor='b', markerfacecolor='None')
plt.grid(True)
plt.xlabel('Number of clusters')
plt.ylabel('Within-cluster Sum of Squares (WSS)')
plt.title('Elbow curve for K-means clustering')

plt.show()

#### If you choose k=3, you can use pairplot to visualize the differences of these 3 clusters in terms of their attributes

References: https://seaborn.pydata.org/generated/seaborn.pairplot.html

In [ ]:
import seaborn as sns
from copy import deepcopy

# Run k-means model
cluster = KMeans(n_clusters=3, random_state=0, n_jobs=-1)
y_pred = cluster.fit_predict(features_std) 

data = deepcopy(iris[feature_list])
data['cluster'] = y_pred
sns.pairplot( data, hue='cluster', diag_kind='kde', markers=['o','s','D'])

The original codes can be found at http://scikit-learn.org/stable/auto_examples/cluster/plot_kmeans_assumptions.html.

### 1.2 Hierarchical Clustering

Hierarchical Clustering Steps:

1. Start with n clusters (each record is its own cluster)
2. Merge two closest records into one cluster
3. At each successive step, the two clusters closest to each other are merged 

In [ ]:
# Load Libraries
from sklearn.cluster import AgglomerativeClustering

In [ ]:
# Create meanshift object
HC = AgglomerativeClustering(n_clusters=3)
HC_model = HC.fit(features_std)

In [ ]:
# Show clusters
HC_model.labels_

In [ ]:
# Plot dendrogram for hierarchical clustering
from scipy.cluster.hierarchy import dendrogram, linkage
avg_link = linkage(features_std[1:20, :], method='average') # Linkage criterion: average distance
dendrogram(avg_link).items

References: https://docs.scipy.org/doc/scipy/reference/cluster.hierarchy.html

More information about hierarchical clustering can be found at: <br/>
[1] http://scikit-learn.org/stable/modules/generated/sklearn.cluster.AgglomerativeClustering.html <br/>
[2] https://docs.scipy.org/doc/scipy/reference/cluster.hierarchy.html

## 2 Assignments on K-Means Clustering (5 points)

**The purpose of this assignment is to know how to use scikit-learn package to do K-Means clustering**

#### Overview

This case requires to develop a customer segmentation to define marketing strategy. The sample Dataset summarizes the usage behavior of about 9000 active credit card holders during the last 6 months. The file is at a customer level with 18 behavioral variables.The dataset can be downloaded here (https://www.kaggle.com/arjunbhasin2013/ccdata/home). It is released under [CC0: Public Domain](https://creativecommons.org/publicdomain/zero/1.0/).

In [ ]:
# Load libraries and dataset
from sklearn import datasets
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.cluster import KMeans

# Load data
feature_list = ['BALANCE', 'PURCHASES', 'CASH_ADVANCE', 'CREDIT_LIMIT', 'PAYMENTS', 'MINIMUM_PAYMENTS']
creditcard = pd.read_csv('./CC GENERAL.csv')[['CUST_ID']+feature_list]
creditcard.head(n=5)

In [ ]:
creditcard.dropna(inplace=True)
creditcard.describe()

#### Question 1. Standardize all the features using `min-max` method (2 points)

An example of standardizing features using `z-index` method:
```python
# Standardize features: z-index standardization
feature_list = ['BALANCE', 'PURCHASES', 'CASH_ADVANCE', 'CREDIT_LIMIT', 'PAYMENTS', 'MINIMUM_PAYMENTS']
scaler = StandardScaler()
features_std = scaler.fit_transform(creditcard[feature_list])
```

References: http://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.MinMaxScaler.html

In [ ]:
# Standardize features: min-max standardization
feature_list = ['BALANCE', 'PURCHASES', 'CASH_ADVANCE', 'CREDIT_LIMIT', 'PAYMENTS', 'MINIMUM_PAYMENTS']

# Initialize a min-max scaler object to do standardization
# Standardize features using min-max method
scaler = MinMaxScaler()
features_std = scaler.fit_transform(creditcard[feature_list])
features_std

#### Question 2. Fit 5-means clustering model with min-max standardized features: k=5 (2 points)
Please:
* Set `n_clusters=5`
* Set `random_state=12345`
* Set `n_jobs=-1` (This may not be necessary)

References: http://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html

In [ ]:
# Fit 5-means clustering model: Suppose 5 clusters k=5
# Create a KMeans clustering model
# Do clustering on min-max standardized features

kmeans = KMeans(n_clusters=5, random_state=12345).fit(features_std)
kmeans.labels_

#### Question 3. Predict which cluster does a new data sample belong to (1 point)

* Suppose new data sample `new_obs=[[40, 90, 100, 1000, 1500, 50]]`
* Use `predict` function
* References: http://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html#sklearn.cluster.KMeans.predict

In [ ]:
# List of cluster centers
kmeans.cluster_centers_

In [ ]:
# Predict which cluster is this new observation in:
new_obs = [[40, 90, 100, 1000, 1500, 50]]

kmeans.predict(new_obs) # New data sample belongs to cluster index 3

## 3 References
[1] Raschka, S. (2015). Python machine learning. Packt Publishing Ltd. <br/>
[2] Chris Albon. (2018). Machine Learning with Python Cookbook. O'Reilly.